server:
  port: 8080

spring:
  datasource:
    username: root
    password: 12345Qwer4321
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: info

indexing-settings:
  sites:
    - url: https://www.radiomv.ru
      name: Radiomv.ru
#    - url: https://www.dimonvideo.ru
#      name: Dimonvideo.ru
#    - url: https://www.lenta.ru
#      name: lenta.ru
    - url: https://www.skillbox.ru
      name: Skillbox.ru
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.ipfran.ru
      name: Ipfran.ru

